# Generated by Django 4.2.9 on 2024-01-30 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=120, unique=True)),
                (
                    "grade",
                    models.FloatField(
                        choices=[
                            (4, "A+"),
                            (3.7, "A"),
                            (3.3, "B+"),
                            (3, "B"),
                            (2.7, "C+"),
                            (2.4, "C"),
                            (2, "D+"),
                            (2, "D"),
                        ]
                    ),
                ),
                (
                    "term",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "First Term"), (2, "Second Term")]
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]
                    ),
                ),
                ("creadit_Hours", models.PositiveSmallIntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
