# Generated by Django 4.2.9 on 2024-01-30 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subName", models.CharField(max_length=120)),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        choices=[
                            ("A+", 4),
                            ("A", 3.7),
                            ("B+", 3.3),
                            ("B", 3),
                            ("C+", 2.7),
                            ("C", 2.4),
                            ("D+", 2),
                            ("D", 2),
                        ]
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
