# Generated by Django 4.2.9 on 2024-01-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="term",
            field=models.PositiveSmallIntegerField(
                choices=[("First Term", 1), ("Second Term", 2)], default=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="year",
            field=models.PositiveSmallIntegerField(
                choices=[("First Term", 1), ("Second Term", 2)], default=1
            ),
            preserve_default=False,
        ),
    ]
