# Generated by Django 4.2.9 on 2024-01-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_subject_term_subject_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="grade",
            field=models.FloatField(
                choices=[
                    (4, "A+"),
                    (3.7, "A"),
                    (3.3, "B+"),
                    (3, "B"),
                    (2.7, "C+"),
                    (2.4, "C"),
                    (2, "D+"),
                    (2, "D"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="term",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "First Term"), (2, "Second Term")]
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="year",
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]
            ),
        ),
    ]
