# Generated by Django 4.2.9 on 2024-01-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_subject_grade_alter_subject_term_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subject",
            old_name="subName",
            new_name="subject_name",
        ),
        migrations.AddField(
            model_name="subject",
            name="creadit_Hours",
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
