# Generated by Django 4.2.9 on 2024-03-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_subject_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subject_name",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
