# Generated by Django 4.2.9 on 2024-03-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_subject_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="ref",
            field=models.SlugField(unique=True),
        ),
    ]
